titles:
  include: ["Engineer", "Developer", "Software", "Data", "DevOps", "ML", "Integration", "Backend", "Python", "AI", "Senior", "Architect", "Solutions", "Technical"]
  exclude: ["Intern", "Junior"]

keywords:
  include:
    - python
    - aws
    - lambda
    - ai
    - ml
    - integration
    - backend
    - senior
    - architect
    - solutions
    - technical
    - developer
    - engineer
    - data
    - devops

  exclude:
    - php
    - cobol

locations:
  include:
    - Remote
    - Anywhere
    - Worldwide
    - USA
    - United States
    - Americas
  exclude:
    - Onsite Only
    - Europe

salary:
  min: 100000            # adjust to your preference
  allow_missing: false
