titles:
  include: ["Engineer", "Developer", "Software", "Data", "DevOps", "ML", "Integration", "Backend", "Python"]
  exclude: ["Intern", "Staff", "Principal"]

keywords:
  include:
    - python
    - aws
    - lambda
  exclude:
    - php
    - cobol

locations:
  include:
    - Remote
    - Anywhere
    - Worldwide
    - USA
    - United States
    - Americas
    - Europe
    - UK
    - Canada
  exclude:
    - Onsite Only